#!/bin/bash
# File: cloudflare-ips-apache-updater/update_ip.sh
# Description: Fetches official Cloudflare IPs, configures mod_remoteip, and fixes Apache LogFormat.
https://github.com/cwswebhosting

# --- Configuration ---
CF_CONF_FILE="/etc/httpd/conf.d/cloudflare.conf"
HTTPD_CONF="/etc/httpd/conf/httpd.conf"
APACHE_SERVICE="httpd"
BACKUP_DIR="/root/apache_backups"

# --- Colors for Output ---
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}[INFO] Starting Cloudflare IP Update...${NC}"

# Ensure backup directory exists
mkdir -p "$BACKUP_DIR"

# 1. Generate Cloudflare Configuration
# ---------------------------------------------------------
echo -e "${YELLOW}[INFO] Downloading latest IP ranges from Cloudflare...${NC}"

# Start creating the file
cat <<EOF > "$CF_CONF_FILE"
# ==============================================================================
# Cloudflare Trusted Proxy Configuration
# Auto-generated by update_ip.sh on $(date)
# ==============================================================================
<IfModule mod_remoteip.c>
    RemoteIPHeader CF-Connecting-IP
EOF

# Fetch IPv4
echo "    # IPv4 Ranges" >> "$CF_CONF_FILE"
curl -s https://www.cloudflare.com/ips-v4 | while read ip; do
    echo "    RemoteIPTrustedProxy $ip" >> "$CF_CONF_FILE"
done

# Fetch IPv6
echo "" >> "$CF_CONF_FILE"
echo "    # IPv6 Ranges" >> "$CF_CONF_FILE"
curl -s https://www.cloudflare.com/ips-v6 | while read ip; do
    echo "    RemoteIPTrustedProxy $ip" >> "$CF_CONF_FILE"
done

# Close block
echo "</IfModule>" >> "$CF_CONF_FILE"

if [ -s "$CF_CONF_FILE" ]; then
    echo -e "${GREEN}[OK] Configuration file generated at $CF_CONF_FILE${NC}"
else
    echo -e "${RED}[ERROR] Failed to generate configuration file. Check internet connection.${NC}"
    exit 1
fi

# 2. Update Apache LogFormat (Safe Sed Replace)
# ---------------------------------------------------------
# We need to change %h (Remote Host) to %a (Client IP) in the 'combined' format
if grep -q 'LogFormat "%h %l %u %t \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\"" combined' "$HTTPD_CONF"; then
    echo -e "${YELLOW}[INFO] Updating LogFormat in $HTTPD_CONF...${NC}"
    
    # Backup
    cp "$HTTPD_CONF" "${BACKUP_DIR}/httpd.conf.bak.$(date +%F_%T)"
    
    # Replace
    sed -i 's/LogFormat "%h %l %u %t \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\"" combined/LogFormat "%a %l %u %t \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\"" combined/' "$HTTPD_CONF"
    
    echo -e "${GREEN}[OK] LogFormat updated to use Real IP (%a).${NC}"
else
    echo -e "${GREEN}[SKIP] LogFormat is already updated or uses a custom format.${NC}"
fi

# 3. Validation and Reload
# ---------------------------------------------------------
echo -e "${YELLOW}[INFO] Verifying Apache syntax...${NC}"

if apachectl -t; then
    echo -e "${GREEN}[OK] Syntax Valid. Reloading Apache...${NC}"
    systemctl reload "$APACHE_SERVICE"
    echo -e "${GREEN}[SUCCESS] Cloudflare IPs updated and Apache reloaded successfully.${NC}"
else
    echo -e "${RED}[ERROR] Syntax Check Failed! Changes not applied. Check $CF_CONF_FILE${NC}"
    exit 1
fi
